name: test
on: push
jobs:
      job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: gcc mandelbrot.c -lm
            - run: sudo apt-get install gnuplot-nox texlive
            - run: gnuplot plot.gpi
            - run: pdflatex art.tex
            - run: pdflatex art.tex
            - run: ls
            - uses: actions/upload-artifact@v4
              with:
                  path: art.pdf
           
          
          
