name: test
on: push
jobs:
    job: 
      runs-on: ubuntu-latest
      steps: 
          - uses: actions/checkout@v4
          - run: gcc mandelbrot.c -lm
          - run: sudo apt-get install gnuplot-nox
          - run: sudo apt-get install texlive 
          - run: gnuplot plot.gpi
          - run: pdflatex art.tex
          - run: path: art.pdf
           
          
          
